name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v2

   #Login no Azure usando as credenciais armazenadas nos secrets
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # Deploy no Azure Static Web App
      - name: Azure Static Web Apps Deploy
        id: azure-static-web-app-deploy
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_API_TOKEN }}
          app_location: '/'
          output_location: 'build'  # Ou o diretório que contém os arquivos prontos para o deploy

        # Condicional de deploy com base no branch
        env:
          AZURE_STATIC_WEB_APP_NAME: ${{ github.ref == 'refs/heads/develop' && 'meu-develop-gerconf' || 'meu-main-gerconf' }}
