name: Workflow para Pull Request para develop

on:
  pull_request:
    branches:
      - develop  # Executa o workflow para PRs feitos para a branch 'develop'
jobs:
  # Job 1: Processo de build e deploy para o Azure Static Web App
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # 5. Atualização do arquivo index.html (se você precisar alterar algo no arquivo antes do deploy)
      - name: Update index.html
        run: |
          sed -i 's/old-text/new-text/g' path/to/index.html  # Exemplo de alteração no arquivo

      # 6. Login no Azure utilizando as credenciais armazenadas no GitHub Secrets
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # 7. Deploy no Azure Static Web Apps
      - name: Deploy to Azure Static Web App
        id: azure-static-web-app-deploy
        uses: azure/static-web-apps-deploy@v0
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_API_TOKEN }}
          app_location: '/'  # Altere conforme a localização do seu código
          output_location: 'build'  # Pasta com o conteúdo final para deploy, normalmente 'build' ou 'dist'
      

#Incluir aqui:
#-	Executar migrações de banco de dados no Supabase.
#DATABASE_URL_DEV=postgresql://postgres.njwinexjugwoaztjfyts:[GABgab@#1234]@aws-0-sa-east-1.pooler.supabase.com:6543/postgres
