name: Deploy Develop

on:
  pull_request:
    branches:
      - develop  # Aciona o workflow quando um PR for aberto para o branch 'develop'

jobs:
  deploy:
    runs-on: ubuntu-latest  # O workflow será executado em um runner Ubuntu

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Rodar as migrações no banco de dados
      - name: Apply migrations to the database
        run: |
          psql -h ${{ secrets.SUPABASE_HOST_DEVELOP }} -U ${{ secrets.SUPABASE_DB_USER_DEVELOP }} -d ${{ secrets.SUPABASE_DB_NAME_DEVELOP }} -f migrations/*.sql
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD_DEVELOP }}  # Passando a senha do banco de dados via variáveis de ambiente
          
      # Passo 3: Deploy do código para o ambiente de desenvolvimento
      - name: Deploy to Azure Static Web App
        uses: azure/static-web-apps-deploy-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}  # Permite a ação de fazer o deploy
          action: "upload"
          app-location: "/"  # Localização do seu app no repositório
          api-location: ""  # Se você tiver uma API, caso contrário deixe vazio
