name: Deploy Main

on:
  schedule:
    - cron: "0 21 * * *"  # Executa todos os dias às 21:00 UTC

jobs:
  deploy:
    runs-on: ubuntu-latest  # O workflow será executado em um runner Ubuntu

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Rodar as migrações no banco de dados
      - name: Apply migrations to the database
        run: |
          psql -h ${{ secrets.SUPABASE_HOST_MAIN }} -U ${{ secrets.SUPABASE_DB_USER_MAIN }} -d ${{ secrets.SUPABASE_DB_NAME_MAIN }} -f migrations/*.sql

      # Passo 3: Deploy do código para o ambiente de produção
      - name: Deploy to Azure Static Web App
        uses: azure/static-web-apps-deploy-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}  # Permite a ação de fazer o deploy
          action: "upload"
          app-location: "/"  # Localização do seu app no repositório
          api-location: "api"  # Se você tiver uma API, caso contrário deixe vazio
